### ISSUE TITLE
Embed google calendar into website

### ISSUE THREAD

**Issue by SpaceTristan** [OpenDataforWeb3/opendataforweb3.github.io#16]
Instead of linking to the google calendar, I think it would be cool to embed the calendar into a webpage on the site.

**Comment by sarob** [comment]
Great idea! I’ll make a new PR for that shortly. Sean ***@***.*** On Jan 8, 2023, at 10:09, Tristan ***@***.***> wrote:﻿
Instead of linking to the google calendar, I think it would be cool to embed the calendar into a webpage on the site.

**Comment by sarob** [comment]
I didn't put a lot of effort in. I was unable to keep the focus on the local page, instead the embed code redirects to the google calendar site.
