### ISSUE TITLE
Add Sandbox project listing and links somewhere on the website

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/opendataforweb3.github.io#36]
Not sure where or how - however we now have a few sandbox projects coming along...

Not urgent IMO vs. the hackathon - however quite useful 

How and where should we place these Sandbox projects on our web site or websites?

Considerations:
- looks good
- easy to maintain 
- tag line & logo contributed by projects (for example - do we create a form for them, or is there someway to just do a PR?)

**Comment by sarob** [comment]
merged with #43
