### ISSUE TITLE
Add a custom URL

### ISSUE THREAD

**Issue by SpaceTristan** [OpenDataforWeb3/opendataforweb3.github.io#4]
Add a custom URL name tbd but I imagine something like the following:

OpenDataCommunity.com
OpenDataCommunity.io
odc.io

Additional naming suggestions and ideas welcome.

**Comment by epowell101** [comment]
We do have OpenDataCommunity.org - and OpenDataCommunity.com and OpenDataCommunity.Foundation

I made @sarob a joint manager on the account as I bought them through a personal account.  I set up a redirect from OpenDataCommunity.org to the prior github.io site and it worked.  So I think it'll just work when we push an updated version

**Comment by sarob** [comment]
Did you get a chance to add my gmail email as the sarob email wasn’t working?Sean ***@***.*** On Dec 29, 2022, at 11:31, Evan Powell ***@***.***> wrote:﻿
We do have OpenDataCommunity.org - and OpenDataCommunity.com and OpenDataCommunity.Foundation
I made @sarob a joint manager on the account as I bought them through a personal account.  I set up a redirect from OpenDataCommunity.org to the prior github.io site and it worked.  So I think it'll just work when we push an updated version
