### ISSUE TITLE
Additional content in posts

### ISSUE THREAD

**Issue by SpaceTristan** [OpenDataforWeb3/opendataforweb3.github.io#5]
We need to add posts and additional content to the website. We will need to establish a process for content submission and plan out reference data/posts to include on the site

**Comment by epowell101** [comment]
I asked about this somewhere as well - where do we put files again for them to become blog posts for example?

**Comment by sarob** [comment]
@SpaceTristan  and @sarob have met and figured out a way to keep the website updated. 

@epowell101 @stefi-says @baokiddy  We all should have a meeting to discuss options.

**Comment by sarob** [comment]
I shared during the weekly meeting. I close this for now and follow up with @epowell101 @stefi-says @baokiddy to catch questions and or updates.
