### ISSUE TITLE
Adjust top level navigation of web site

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/opendataforweb3.github.io#9]
Not sure if these should be their own issue.  Grouping them here:

1.  "DOCS" on top level c/d instead be "Resources" -> we do not have DOCS really as people think about it; 

2.  The https://spacetristan.github.io/opendataforweb3.github.io/docs/  currently lists "RESOURCES" at the end -> this links to Landscape; could we
a) Change Resources to Landscape?
b) Put Landscape at the top?
 
3.  Landscape (here:  https://spacetristan.github.io/opendataforweb3.github.io/docs/help/resources/) here currently does not have the introductory text for landscape from:  https://github.com/OpenDataforWeb3
This is probably because when the Landscape was restructured into a different read me by @sarob this part was left out as it was in a different file:  "One of our projects is to collectively curate useful solutions that enable data analysts to find insights while remaining decentralized. Your feedback and input into the Landscape and all other materials we publish is hugely valuable - as are your stars on the repository and amplification on social media." 
Can we add to the Landscape file?  

4. Instead of Get Started on the top level perhaps we just have an "About Us"
- we can link to the Notion site from @Curi0usRabbit 

5.  We of course don't need the license info on the front page
- please remove the license information

6. The Blog - where do we start adding those files?

**Comment by SpaceTristan** [comment]
I think it might be a good idea to break this all out into different issues. Might be easier to divide and conquer. Also to see progress and track potential issues that may come up.

**Comment by SpaceTristan** [comment]
#11 adds fixes for 5 on the list

**Comment by SpaceTristan** [comment]
> #11 adds fixes for 5 on the list

Also added in 4

**Comment by sarob** [comment]
@SpaceTristan and @sarob met to discuss a new sitemap for https://opendataforweb3.github.io

@sarob will create a new issue to discuss managing the website content options with the website team

@sarob submitted https://github.com/OpenDataforWeb3/Landscape/pull/52 to move files to match the new site

@SpaceTristan is going to update opendataforweb3.github.io to match 

![Image](https://user-images.githubusercontent.com/1191994/210114535-5a1c8674-7bd8-4099-b649-cfb020687da8.png)

**Comment by SpaceTristan** [comment]
Updated site to match sitemap in PR #12

**Comment by sarob** [comment]
new PR #13

**Comment by SpaceTristan** [comment]
I think we could mark this "Done" maybe @epowell101 can take a look before we mark it as such?

**Comment by epowell101** [comment]
looks good
